"""
Template definitions — 18 distinct templates across 4 categories
Each has unique typography, palette, spacing, cover, header/footer
"""

TEMPLATES = [
    # Developer
    {
        "id": "terminal",
        "name": "Terminal",
        "category": "Developer",
        "description": "Monospace, dark cover, matrix-green accents. For hackers.",
        "preview_colors": ["#0a0a0a","#00ff88","#1a1a1a"],
        "colors": {"primary":"#00FF88","secondary":"#0A0A0A","accent":"#00CC6A","bg":"#0A0A0A","text":"#E5E7EB","muted":"#6B7280","card":"#141414","line":"#1F2937"},
        "fonts": {"heading":"Courier-Bold","body":"Courier","mono":"Courier"},
        "spacing": "compact",
        "cover_style": "terminal",
        "header_style": "mono_line",
    },
    {
        "id": "github",
        "name": "GitHub",
        "category": "Developer",
        "description": "Clean repo-style, octocat grayscale + blue.",
        "preview_colors": ["#0d1117","#58a6ff","#ffffff"],
        "colors": {"primary":"#0969DA","secondary":"#24292F","accent":"#58A6FF","bg":"#FFFFFF","text":"#24292F","muted":"#656D76","card":"#F6F8FA","line":"#D0D7DE"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "comfortable",
        "cover_style": "github",
        "header_style": "underline",
    },
    {
        "id": "cyber",
        "name": "Cyber",
        "category": "Developer",
        "description": "Neon cyan/magenta on deep navy. Futuristic.",
        "preview_colors": ["#020617","#06ffa5","#ff00a0"],
        "colors": {"primary":"#06FFA5","secondary":"#020617","accent":"#FF00A0","bg":"#020617","text":"#E2E8F0","muted":"#64748B","card":"#0F172A","line":"#1E293B"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier-Bold"},
        "spacing": "airy",
        "cover_style": "cyber",
        "header_style": "neon",
    },
    {
        "id": "architecture",
        "name": "Architecture",
        "category": "Developer",
        "description": "Blueprint grid, technical line-drawings.",
        "preview_colors": ["#0b3d5f","#38bdf8","#e0f2fe"],
        "colors": {"primary":"#0B3D5F","secondary":"#0284C7","accent":"#38BDF8","bg":"#F8FAFC","text":"#0F172A","muted":"#64748B","card":"#FFFFFF","line":"#CBD5E1"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "comfortable",
        "cover_style": "blueprint",
        "header_style": "ruled",
    },
    {
        "id": "minimal-code",
        "name": "Minimal Code",
        "category": "Developer",
        "description": "Ultra-minimal, whitespace, tiny captions.",
        "preview_colors": ["#ffffff","#111111","#eeeeee"],
        "colors": {"primary":"#111111","secondary":"#6B7280","accent":"#111111","bg":"#FFFFFF","text":"#111827","muted":"#9CA3AF","card":"#F9FAFB","line":"#E5E7EB"},
        "fonts": {"heading":"Helvetica","body":"Helvetica","mono":"Courier"},
        "spacing": "airy",
        "cover_style": "minimal",
        "header_style": "minimal",
    },
    # Professional
    {
        "id": "corporate",
        "name": "Corporate",
        "category": "Professional",
        "description": "Navy + gold executive corporate.",
        "preview_colors": ["#0f1e3a","#c9a86a","#ffffff"],
        "colors": {"primary":"#0F1E3A","secondary":"#C9A86A","accent":"#B5955A","bg":"#FFFFFF","text":"#1E293B","muted":"#64748B","card":"#F8FAFC","line":"#E2E8F0"},
        "fonts": {"heading":"Times-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "comfortable",
        "cover_style": "corporate",
        "header_style": "gold_rule",
    },
    {
        "id": "executive",
        "name": "Executive",
        "category": "Professional",
        "description": "Charcoal + teal, bold metrics.",
        "preview_colors": ["#1a1f2e","#14b8a6","#f1f5f9"],
        "colors": {"primary":"#14B8A6","secondary":"#1A1F2E","accent":"#0F766E","bg":"#F8FAFC","text":"#1E293B","muted":"#64748B","card":"#FFFFFF","line":"#E2E8F0"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "compact",
        "cover_style": "executive",
        "header_style": "block",
    },
    {
        "id": "modern-portfolio",
        "name": "Modern Portfolio",
        "category": "Professional",
        "description": "Warm cream, rounded cards, soft editorial.",
        "preview_colors": ["#fdf6ec","#ff6b35","#1a1a1a"],
        "colors": {"primary":"#FF6B35","secondary":"#1A1A1A","accent":"#FF8C61","bg":"#FDF6EC","text":"#1A1A1A","muted":"#78716C","card":"#FFFFFF","line":"#E7E5E4"},
        "fonts": {"heading":"Times-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "airy",
        "cover_style": "portfolio",
        "header_style": "rounded",
    },
    {
        "id": "case-study",
        "name": "Case Study",
        "category": "Professional",
        "description": "Left-rule editorial, outcome metrics.",
        "preview_colors": ["#ffffff","#dc2626","#171717"],
        "colors": {"primary":"#DC2626","secondary":"#171717","accent":"#991B1B","bg":"#FFFFFF","text":"#171717","muted":"#737373","card":"#FAFAFA","line":"#E5E5E5"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "comfortable",
        "cover_style": "case",
        "header_style": "left_rule",
    },
    # Academic
    {
        "id": "college",
        "name": "College Project",
        "category": "Academic",
        "description": "Traditional academic, crest-like, serif headings.",
        "preview_colors": ["#1e3a8a","#ffffff","#fbbf24"],
        "colors": {"primary":"#1E3A8A","secondary":"#FBBF24","accent":"#1E40AF","bg":"#FFFFFF","text":"#1F2937","muted":"#6B7280","card":"#F3F4F6","line":"#D1D5DB"},
        "fonts": {"heading":"Times-Bold","body":"Times-Roman","mono":"Courier"},
        "spacing": "comfortable",
        "cover_style": "college",
        "header_style": "academic",
    },
    {
        "id": "internship",
        "name": "Internship Report",
        "category": "Academic",
        "description": "Formal, navy, table-heavy, certificate feel.",
        "preview_colors": ["#0f2a44","#e2e8f0","#38bdf8"],
        "colors": {"primary":"#0F2A44","secondary":"#38BDF8","accent":"#0EA5E9","bg":"#FFFFFF","text":"#0F172A","muted":"#64748B","card":"#F1F5F9","line":"#CBD5E1"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "compact",
        "cover_style": "internship",
        "header_style": "boxed",
    },
    {
        "id": "research",
        "name": "Research Report",
        "category": "Academic",
        "description": "Serif, citations, muted gray/blue scholarly.",
        "preview_colors": ["#f8fafc","#475569","#0f172a"],
        "colors": {"primary":"#334155","secondary":"#475569","accent":"#0F172A","bg":"#FFFFFF","text":"#1E293B","muted":"#64748B","card":"#F8FAFC","line":"#E2E8F0"},
        "fonts": {"heading":"Times-Bold","body":"Times-Roman","mono":"Courier"},
        "spacing": "airy",
        "cover_style": "research",
        "header_style": "serif_rule",
    },
    {
        "id": "technical",
        "name": "Technical Report",
        "category": "Academic",
        "description": "Mono + sans, code blocks, spec-sheet.",
        "preview_colors": ["#111827","#10b981","#e5e7eb"],
        "colors": {"primary":"#10B981","secondary":"#111827","accent":"#059669","bg":"#FFFFFF","text":"#111827","muted":"#6B7280","card":"#F9FAFB","line":"#E5E7EB"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier-Bold"},
        "spacing": "compact",
        "cover_style": "technical",
        "header_style": "mono_box",
    },
    # Creative
    {
        "id": "neon",
        "name": "Neon",
        "category": "Creative",
        "description": "Black + neon pink/cyan glowing accents.",
        "preview_colors": ["#000000","#ff0080","#00ffff"],
        "colors": {"primary":"#FF0080","secondary":"#00FFFF","accent":"#FF0080","bg":"#0A0A0A","text":"#FFFFFF","muted":"#A1A1AA","card":"#18181B","line":"#27272A"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier-Bold"},
        "spacing": "comfortable",
        "cover_style": "neon",
        "header_style": "glow",
    },
    {
        "id": "glass",
        "name": "Glass",
        "category": "Creative",
        "description": "Frosted translucent cards, soft gradients.",
        "preview_colors": ["#e0e7ff","#6366f1","#ffffff"],
        "colors": {"primary":"#6366F1","secondary":"#8B5CF6","accent":"#EC4899","bg":"#F5F3FF","text":"#1E1B4B","muted":"#6B7280","card":"#FFFFFF","line":"#DDD6FE"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "airy",
        "cover_style": "glass",
        "header_style": "soft",
    },
    {
        "id": "editorial",
        "name": "Editorial",
        "category": "Creative",
        "description": "Magazine serif, asymmetry, pull-quotes.",
        "preview_colors": ["#fafaf9","#1c1917","#e7cc8f"],
        "colors": {"primary":"#1C1917","secondary":"#E7CC8F","accent":"#A16207","bg":"#FAFAF9","text":"#1C1917","muted":"#78716C","card":"#FFFFFF","line":"#E7E5E4"},
        "fonts": {"heading":"Times-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "airy",
        "cover_style": "editorial",
        "header_style": "oversize",
    },
    {
        "id": "magazine",
        "name": "Magazine",
        "category": "Creative",
        "description": "Bold grid, strong typographic hierarchy.",
        "preview_colors": ["#dc2626","#ffffff","#171717"],
        "colors": {"primary":"#171717","secondary":"#DC2626","accent":"#DC2626","bg":"#FFFFFF","text":"#171717","muted":"#52525B","card":"#F4F4F5","line":"#E4E4E7"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier-Bold"},
        "spacing": "compact",
        "cover_style": "magazine",
        "header_style": "grid",
    },
    {
        "id": "timeline",
        "name": "Timeline",
        "category": "Creative",
        "description": "Horizontal timeline, chronological steps.",
        "preview_colors": ["#fef3c7","#d97706","#78350f"],
        "colors": {"primary":"#D97706","secondary":"#78350F","accent":"#F59E0B","bg":"#FFFBEB","text":"#451A03","muted":"#92400E","card":"#FFFFFF","line":"#FDE68A"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier"},
        "spacing": "comfortable",
        "cover_style": "timeline",
        "header_style": "timeline",
    },
    {
        "id": "chatgpt",
        "name": "ChatGPT",
        "category": "Creative",
        "description": "ChatGPT conversational — clean Inter, chat bubbles, code blocks, green accent.",
        "preview_colors": ["#ffffff","#10a37f","#f7f7f8"],
        "colors": {"primary":"#10A37F","secondary":"#202123","accent":"#19C37D","bg":"#FFFFFF","text":"#343541","muted":"#6E6E80","card":"#F7F7F8","line":"#E5E5E5"},
        "fonts": {"heading":"Helvetica-Bold","body":"Helvetica","mono":"Courier-Bold"},
        "spacing": "comfortable",
        "cover_style": "chatgpt",
        "header_style": "chatgpt",
    },
]

def get_template(tid: str):
    for t in TEMPLATES:
        if t["id"] == tid:
            return t
    return TEMPLATES[1]  # github default

def list_templates():
    return TEMPLATES
